name: Deploy to Vultr Server

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vultr Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          script: |
            cd /var/www/andilembele.com
            # Fix git ownership issue first
            git config --global --add safe.directory /var/www/andilembele.com
            git pull origin main
            # Use sudo for privileged operations
            sudo chown -R www-data:www-data /var/www/andilembele.com
            sudo chmod -R 755 /var/www/andilembele.com
            sudo systemctl reload nginx
            sudo sh -c 'echo "Deployment completed at $(date)" >> /var/log/deploy.log'

      - name: Verify deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          script: |
            curl -f -I https://andilembele.com || exit 1
            echo "Website is accessible"
            # Also check nginx status
            sudo systemctl status nginx --no-pager || echo "Nginx status check failed but continuing..."

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Deployment successful! Website is live at https://andilembele.com"
          else
            echo "❌ Deployment failed. Check the logs for details."
          fi
