name: Deploy to Vultr Server

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vultr Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          script: |
            cd /var/www/andilembele.com
            # Fix git ownership issue first
            git config --global --add safe.directory /var/www/andilembele.com
            # Reset git permissions to allow pull
            chmod -R 755 .git
            git pull origin main
            # Set proper permissions for web files (without sudo)
            chmod -R 644 *.html *.css *.js *.ico *.svg *.xml *.txt *.webmanifest *.pdf
            chmod -R 644 images/*
            chmod 755 images/
            chmod 755 .
            # Create deployment log in user's home directory
            echo "Deployment completed at $(date)" >> ~/deploy.log

      - name: Verify deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          script: |
            curl -f -I https://andilembele.com || exit 1
            echo "Website is accessible"
            # Check if deployment log was created
            if [ -f ~/deploy.log ]; then
              echo "Deployment log found:"
              tail -1 ~/deploy.log
            else
              echo "No deployment log found"
            fi

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Deployment successful! Website is live at https://andilembele.com"
          else
            echo "❌ Deployment failed. Check the logs for details."
          fi
